### ISSUE TITLE
github markdown link

### ISSUE THREAD

**Issue by Phillip-D-Shields** [nmit-it-students-association/resources#2]
github markdown link should be moved to git section towards top?

**Comment by Phillip-D-Shields** [comment]
and maybe change 'git links' section title to 'github links'

**Comment by jordan-huitema** [comment]
We should move the Markdown Cheatsheet to the top with the other github Mastering Markdown Link

**Comment by Phillip-D-Shields** [comment]
the markdown cheatsheet isnt an official github documentation, so i figured best to keep it separated
